name: Vite React CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup-NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          #cache: 'npm'

     # - name: Install dependencies
     #   run: npm ci

      - name: Build Vite Project
        run: npm run build
        
        
        
      
      
    
